namespace: dev

frontend:
  repository:
    image: abhishek00007/poc-angular-app:8.0
  replicas: 1
  target:
    port: 80
  service:
    port: 8081  
  ingress:
    host: dev-frontend.nginxonline.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

