apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port | default 8081 }}
      targetPort: {{ .Values.frontend.target.port | default 80 }}
  type: ClusterIP

  
