namespace: dev

backend:
  repository:
    image: abhishek00007/poc-spring-app:7.0
  replicas: 1
  service:
    port: 8080
  ingress:
    host: dev-backend.nginxonline.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
